### ISSUE TITLE
Noob error running plugin

### ISSUE THREAD

**Issue by ghost** [AdStage/newrelic-s3-plugin#1]
Hi!

I download your plugin, but when run it (after edited license & credentials) doesn't work

```
root@CMD-KALTURA-DEVOPS01 newrelic-s3-plugin # ./newrelic_s3_agent 
./newrelic_s3_agent:23: syntax error, unexpected ':', expecting ')'
        credentials: Aws::Credentials.new(access_k...
                    ^
./newrelic_s3_agent:23: syntax error, unexpected ',', expecting kEND
./newrelic_s3_agent:25: syntax error, unexpected ':', expecting ')'
      s3.list_objects(bucket: bucket_name).each do |page|
                             ^
```

My newrelic_plugin.yml looks like this

```
# Please make sure to update the license_key information with the license key for your New Relic
# account.
#
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  verbose: 1

  # Proxy configuration:
  #proxy:
  #  address: localhost
  #  port: 8080
  #  user: nil
  #  password: nil

# Use this shared block if all your buckets use the same AWS
#   credentials. Can use other values for each bucket, though.
s3_creds: &s3_creds
  access_key_id: 'XXXXXXXXXXXXXXXXXXXXX'
  secret_access_key: 'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP'
#
# Agent Configuration:
#
agents:
  s3:
    - bucket_name: agea
      region: us-east-1
      <<: *s3_creds
```

Can you help...?
thanks
